/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Procesos.*;
import SistemaBD.*;
import factory.Factory;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roban
 */
public class PlanCompra extends javax.swing.JFrame {
    private static Factory factory;
    static String usuario;
    static int id_personal;
    static int id_persona;
    /**
     * Creates new form PlanCompra 
     */
    public PlanCompra(String usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        factory = new Factory();
        this.usuario = usuario;
        cargarColumnasTabla();
        BaseDatos base = factory.baseDatos();
        UsuarioBD perfil = base.obtenerUsuario(usuario);
        id_persona = perfil.getId_persona();
        cargarModeloTabla(usuario);
    }
    
    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    private void cargarColumnasTabla(){
        
        modeloTabla.addColumn("ID Producto");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Vendedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Unidad");
    }
    
    private void cargarModeloTabla(String usuario){
        BaseDatos base = factory.baseDatos();
        ArrayList<ProductosVenta> listaInventario = base.obtenerTodosProductos();
        
        int numeroVendedores = listaInventario.size();
        modeloTabla.setNumRows(numeroVendedores);
        
        for(int i =0;i<numeroVendedores;i++){
            ProductosVenta productosV = listaInventario.get(i);
            int id_persona = productosV.getId_persona();
            UsuarioBD vendedor = base.obtenerVendedorbyID(id_persona);
            int id_producto = productosV.getId_producto();
            String Producto = productosV.getProducto();
            Double precio = productosV.getPrecio();
            Double cantidad  = productosV.getCantidad();
            String unidad = productosV.getUnidad();
            String descripcion = productosV.getDescripcion();
            modeloTabla.setValueAt(id_producto, i, 0);
            modeloTabla.setValueAt(Producto, i, 1);
            modeloTabla.setValueAt(descripcion, i, 2);
            modeloTabla.setValueAt(vendedor.getNombre(), i, 3);
            modeloTabla.setValueAt(precio, i, 4);
            modeloTabla.setValueAt(cantidad, i, 5);
            modeloTabla.setValueAt(unidad, i, 6);
            
        }
    }
    
    private void Busqueda_cargarModeloTabla(String usuario){
        BaseDatos base = factory.baseDatos();
        String busqueda = this.txt_buscar.getText();
        ArrayList<ProductosVenta> listaInventario = base.BuscarTodosProductos(busqueda);
        
        int numeroVendedores = listaInventario.size();
        modeloTabla.setNumRows(numeroVendedores);
        
        for(int i =0;i<numeroVendedores;i++){
            ProductosVenta productosV = listaInventario.get(i);
            int id_persona = productosV.getId_persona();
            UsuarioBD vendedor = base.obtenerVendedorbyID(id_persona);
            int id_producto = productosV.getId_producto();
            String Producto = productosV.getProducto();
            Double precio = productosV.getPrecio();
            Double cantidad  = productosV.getCantidad();
            String unidad = productosV.getUnidad();
            String descripcion = productosV.getDescripcion();
            modeloTabla.setValueAt(id_producto, i, 0);
            modeloTabla.setValueAt(Producto, i, 1);
            modeloTabla.setValueAt(descripcion, i, 2);
            modeloTabla.setValueAt(vendedor.getNombre(), i, 3);
            modeloTabla.setValueAt(precio, i, 4);
            modeloTabla.setValueAt(cantidad, i, 5);
            modeloTabla.setValueAt(unidad, i, 6);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_atras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_productosDisponibles = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_todos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plan de Compra");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrando(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_atras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1168, 11, -1, -1));

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 140, 1189, 419));

        lbl_productosDisponibles.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_productosDisponibles.setForeground(new java.awt.Color(240, 240, 240));
        lbl_productosDisponibles.setText("Productos Disponibles");
        getContentPane().add(lbl_productosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 295, -1));

        lbl_buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_buscar.setForeground(new java.awt.Color(240, 240, 240));
        lbl_buscar.setText("Buscar Producto");
        getContentPane().add(lbl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        btn_todos.setText("Mostrar Todos");
        btn_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vendedor/fobdo6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrando
            GUICliente cliente = factory.GUIprincipal(usuario);
            cliente.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_cerrando
   
    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        this.Busqueda_cargarModeloTabla(usuario);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todosActionPerformed
        this.cargarModeloTabla(usuario);
    }//GEN-LAST:event_btn_todosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanCompra(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_productosDisponibles;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
