/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import factory.Factory;
import Procesos.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import SistemaBD.*;

/**
 *
 * @author roban
 */
public class ProductosVendedor extends javax.swing.JFrame {
    private static Factory factory;
    static String usuario;
    
    
    /**
     * Creates new form ProductosVendedor
     */
    public ProductosVendedor(String usuario) {
        factory = new Factory();
        this.usuario = usuario;
        initComponents();
        cargarColumnasTabla();
        cargarModeloTabla(usuario);
        this.lbl_usuario.setText("Usuario: "+usuario);
    }
    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    private void cargarColumnasTabla(){
        
        modeloTabla.addColumn("ID Producto");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Unidad");
        
    }

    private void insertarProductoVendedor(int ID_persona){
        BaseDatos base = factory.baseDatos();
        int id_item = 0;
        int id_persona = ID_persona;
        String Producto = this.txt_producto.getText();
        String descripcion = this.txt_descripcion.getText();
        Double cantidad = Double.parseDouble(this.txt_cantidad.getText());
        Double precio = Double.parseDouble(this.txt_precio.getText());
        String unidad = this.txt_unidad.getText();
        
        ProductosVenta nuevoProductoVendedor = factory.productosVenta(id_item,id_persona, Producto,precio , cantidad, unidad, descripcion);
        base.insertarProductoVendedor(nuevoProductoVendedor);
    }
    
    private void cargarModeloTabla(String usuario){
        BaseDatos base = factory.baseDatos();
        ArrayList<ProductosVenta> listaInventario = base.obtenerProductos(base.obtenerID(usuario));
        int numeroVendedores = listaInventario.size();
        modeloTabla.setNumRows(numeroVendedores);
        
        for(int i =0;i<numeroVendedores;i++){
            ProductosVenta productosV = listaInventario.get(i);
            
            int id_producto = productosV.getId_producto();
            int id_persona = productosV.getId_persona();
            String Producto = productosV.getProducto();
            Double precio = productosV.getPrecio();
            Double cantidad  = productosV.getCantidad();
            String unidad = productosV.getUnidad();
            String descripcion = productosV.getDescripcion();
            
            
            modeloTabla.setValueAt(id_producto, i, 0);
            modeloTabla.setValueAt(Producto, i, 1);
            modeloTabla.setValueAt(descripcion, i, 2);
            modeloTabla.setValueAt(precio, i, 3);
            modeloTabla.setValueAt(cantidad, i, 4);
            modeloTabla.setValueAt(unidad, i, 5);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_atras = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        txt_producto = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_unidad = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        lbl_producto = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_unidad = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        lbl_insertar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos - Vendedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrando(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 260, 1126, 299));

        btn_atras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 90, 20));

        lbl_usuario.setText("Usuario:");
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 26, -1, -1));
        getContentPane().add(txt_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 20));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, 20));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 50, 20));
        getContentPane().add(txt_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 110, 20));
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 200, 20));

        lbl_producto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_producto.setForeground(new java.awt.Color(240, 240, 240));
        lbl_producto.setText("Producto:");
        getContentPane().add(lbl_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        lbl_precio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_precio.setForeground(new java.awt.Color(240, 240, 240));
        lbl_precio.setText("Precio:");
        getContentPane().add(lbl_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        lbl_cantidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(240, 240, 240));
        lbl_cantidad.setText("Cantidad:");
        getContentPane().add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        lbl_descripcion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(240, 240, 240));
        lbl_descripcion.setText("Descripcion:");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        lbl_unidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_unidad.setForeground(new java.awt.Color(240, 240, 240));
        lbl_unidad.setText("Unidades:");
        getContentPane().add(lbl_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        btn_agregar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        lbl_insertar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_insertar.setForeground(new java.awt.Color(240, 240, 240));
        lbl_insertar.setText("Insertar nuevo producto");
        getContentPane().add(lbl_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/provendedor/productapplication_producto_3010.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -120, 620, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/provendedor/fondo8_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void cerrando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrando
        GUIVendedor vendedor = factory.GUIvendedor(usuario);
        vendedor.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cerrando

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        BaseDatos base = factory.baseDatos();
        this.insertarProductoVendedor(base.obtenerID(usuario));
    }//GEN-LAST:event_btn_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosVendedor(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_insertar;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_producto;
    private javax.swing.JLabel lbl_unidad;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_producto;
    private javax.swing.JTextField txt_unidad;
    // End of variables declaration//GEN-END:variables
}
